<?php 
// application/layouts/scripts/image.phtml
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" > 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>Edit Image</title>
	<?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
	<?php echo $this->headScript(); ?>
</head>

<body class="launched" onload="window.focus()" >
	<div id="content" >
  <?php echo $this->layout()->content ?>
  </div>
</body>
</html>