<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
</head>

<body>
<div id="container" >
<h1>Exemplify</h1>
<?php echo $this->layout()->content; ?>
</div>
</body>
</html>
