<?php
$mmCat = get_class($this->rowset->getTable());
?>
<h5><a href="#" onclick="launchMMEdit('<?php echo get_class($this->srcRow->getTable()) ?>', '<?php echo $this->srcRow->getID(); ?>' , '<?php echo $mmCat?>' )" title="edit connections to <?php echo $this->rowset->getTable()->getPlural(); ?>" >
<img src="<?php echo ICON_PATH; ?>/table_relationship.png" /></a> <?php echo $this->rowset->getTable()->getPlural(); ?></h5>
<?php if(count($this->rowset)) { ?>
<div class="scroll" >
<ul>
	<?php 
	foreach($this->rowset as $mmRow) {  ?>
	<li><a href="<?php echo BASE; ?>/edit/show/cat/<?php echo $mmCat; ?>/id/<?php echo $mmRow->getID(); ?>" ><?php echo $mmRow->getTitle(); ?></a></li>
<?php	} ?>
</ul>
</div>
<?php } ?>